name: Run tests on push to main and pull requests

on:
  push:
    branches: [ "main"]
  pull_request:
    branches: [ "main"]


jobs:
  test:
    runs-on: macos-latest
    permissions: 
      contents: read
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Change directory to candycrush to execute gradle commands from project root
        run: cd candycrush

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'



      - name: Grant execute permision for Gradle
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test
