
name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    # Configure Gradle for optimal use in GiHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Change directory to candycrush to execute gradle commands from project root
      run: cd candycrush
    

    - name: give permission
      working-directory: ./candycrush
      run: chmod +x gradlew

    - name: Build with Gradle Wrapper
      working-directory: ./candycrush
      run: ./gradlew build

    - name: Run tests
      working-directory: ./candycrush
      run: ./gradlew test
